version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: rumahwarga_db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: rumahwarga
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: rumahwarga_backend
    ports:
      - "3001:3001"
    env_file:
      - ./backend/.env
    environment:
      - DATABASE_URL=postgresql://root:password@db:5432/rumahwarga?schema=public
      - JWT_SECRET=super-secret-jwt-key
    depends_on:
      - db

volumes:
  postgres_data:
